markers:
  -
    header:
      seq: 0
      stamp:
        secs: 1651003161
        nsecs: 766932964
      frame_id: "/camera_color_optical_frame"
    ns: ''
    id: 130
    type: 1
    action: 0
    pose:
      position:
        x: 0.0241800574487
        y: -0.0342552404967
        z: 0.969235731015
      orientation:
        x: 0.999344598409
        y: -0.00832851725226
        z: -0.0112885233133
        w: 0.0333703262417
    scale:
      x: 0.047
      y: 0.047
      z: 0.005
    color:
      r: 1.0
      g: 0.0
      b: 0.705882370472
      a: 0.330000013113
    lifetime:
      secs: 0
      nsecs: 200000000
    frame_locked: False
    points: []
    colors: []
    text: "base_left"
    mesh_resource: ''
    mesh_use_embedded_materials: False
  -
    header:
      seq: 0
      stamp:
        secs: 1651003161
        nsecs: 766932964
      frame_id: "/camera_color_optical_frame"
    ns: ''
    id: 131
    type: 1
    action: 0
    pose:
      position:
        x: 0.0920780699485
        y: -0.0335624826098
        z: 0.968065369117
      orientation:
        x: 0.999093130014
        y: -0.00356607996036
        z: -0.0204699706518
        w: 0.0371642426745
    scale:
      x: 0.047
      y: 0.047
      z: 0.005
    color:
      r: 0.611764729023
      g: 0.0
      b: 1.0
      a: 0.330000013113
    lifetime:
      secs: 0
      nsecs: 200000000
    frame_locked: False
    points: []
    colors: []
    text: "base_right"
    mesh_resource: ''
    mesh_use_embedded_materials: False
  -
    header:
      seq: 0
      stamp:
        secs: 1651003161
        nsecs: 766932964
      frame_id: "/camera_color_optical_frame"
    ns: ''
    id: 132
    type: 1
    action: 0
    pose:
      position:
        x: 0.0129902026683
        y: -0.0928715676789
        z: 0.972609772983
      orientation:
        x: 0.992153145926
        y: 0.0146480995898
        z: -0.0982938952781
        w: 0.0758675052842
    scale:
      x: 0.0235
      y: 0.0235
      z: 0.005
    color:
      r: 0.0
      g: 0.0705882385373
      b: 1.0
      a: 0.330000013113
    lifetime:
      secs: 0
      nsecs: 200000000
    frame_locked: False
    points: []
    colors: []
    text: "wrist_inside"
    mesh_resource: ''
    mesh_use_embedded_materials: False
  -
    header:
      seq: 0
      stamp:
        secs: 1651003161
        nsecs: 766932964
      frame_id: "/camera_color_optical_frame"
    ns: ''
    id: 133
    type: 1
    action: 0
    pose:
      position:
        x: 0.0544769741546
        y: -0.092754424718
        z: 0.970924466667
      orientation:
        x: 0.999674792188
        y: -0.00628684941704
        z: 0.0109935765558
        w: -0.0221342870211
    scale:
      x: 0.0235
      y: 0.0235
      z: 0.005
    color:
      r: 0.0
      g: 0.752941191196
      b: 1.0
      a: 0.330000013113
    lifetime:
      secs: 0
      nsecs: 200000000
    frame_locked: False
    points: []
    colors: []
    text: "wrist_top"
    mesh_resource: ''
    mesh_use_embedded_materials: False
  -
    header:
      seq: 0
      stamp:
        secs: 1651003161
        nsecs: 766932964
      frame_id: "/camera_color_optical_frame"
    ns: ''
    id: 134
    type: 1
    action: 0
    pose:
      position:
        x: 0.100040371589
        y: -0.0892338916474
        z: 0.971143314039
      orientation:
        x: 0.999737501831
        y: -0.00162452511204
        z: 0.00672076359396
        w: -0.0218430695578
    scale:
      x: 0.0314
      y: 0.0314
      z: 0.005
    color:
      r: 0.0
      g: 1.0
      b: 0.564705908298
      a: 0.330000013113
    lifetime:
      secs: 0
      nsecs: 200000000
    frame_locked: False
    points: []
    colors: []
    text: "shoulder_top"
    mesh_resource: ''
    mesh_use_embedded_materials: False
