testrig_aruco_marker_info:
  base_left_marker_pose:
  - - 1.0
    - 0.0
    - 0.0
    - 0.009
  - - 0.0
    - 1.0
    - 0.0
    - -0.06418
  - - 0.0
    - 0.0
    - 1.0
    - 0.97551
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  base_right_marker_pose:
  - - 1.0
    - 0.0
    - 0.0
    - 0.078
  - - 0.0
    - 1.0
    - 0.0
    - -0.06418
  - - 0.0
    - 0.0
    - 1.0
    - 0.97551
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  shoulder_marker_pose:
  - - 1.0
    - 0.0
    - 0.0
    - 0.0858
  - - 0.0
    - 1.0
    - 0.0
    - -0.12048
  - - 0.0
    - 0.0
    - 1.0
    - 0.97551
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  wrist_inside_marker_pose:
  - - 1.0
    - 0.0
    - 0.0
    - -0.00275
  - - 0.0
    - 1.0
    - 0.0
    - -0.12443
  - - 0.0
    - 0.0
    - 1.0
    - 0.97551
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  wrist_top_marker_pose:
  - - 1.0
    - 0.0
    - 0.0
    - 0.03935
  - - 0.0
    - 1.0
    - 0.0
    - -0.12443
  - - 0.0
    - 0.0
    - 1.0
    - 0.97551
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
